FORMAT: 1A
HOST: https://129.213.15.72/mikarinneoracle/

# jscreditscore

Returns person's credit score based on personal information.

## Credit score [/creditscore]

### Gets person's credit score [POST]

+ Response 200 (application/json)

            {
                "firstname": "Mika",
                "lastname": "Rinne",
                "ssn": "111-22-3333",
                "dateofbirth": "01/29/1970",
                "score": 620
            }